[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd functions && npm install"

[deploy]
startCommand = "node functions/server.js"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
